### ISSUE TITLE
autosub not downloading subtitles from addic7ed?

### ISSUE THREAD

**Issue by JohnK24** [Donny87/autosub-bootstrapbill#132]
I'm trying autosub but it seems not to download addic7ed subtitles?
I have Orange is the new black season 3 (webdl - NTb release) here. 
Autosub is not downloading any dutch subtitle at all while the subtitles are available on addic7ed.

Any idea what could be the problem?

**Comment by Donny87** [comment]
Not enough information, and addic7ed is working fine for others.
