### ISSUE TITLE
Error retrieving MyPanel from Addic7ed

### ISSUE THREAD

**Issue by basroijen** [Donny87/autosub-bootstrapbill#134]
Hi,

Autosub always gives the following error for Addic7ed: "Addic7edAPI: Couldn't retrieve Addic7ed MyPanel data"
The test-button always finishes successful.
I already tried changing my password so it doesn't any special characters.
I'm currently using AUTO-SUB BOOTSTRAP BILL ALPHA 0.6.2 on a QNAP.

**Comment by Donny87** [comment]
probably related to your version of Python, what version do you have at the moment?

**Comment by basroijen** [comment]
I'm using Python version 2.6.7

Op donderdag 23 juli 2015 heeft Donny87 <notifications@github.com> het
volgende geschreven:

**Comment by basroijen** [comment]
Just noticed the minimum requirement of Python 2.7 in the readme (wasn't meedeed begore So I didn't check), going to try that first and report back
