### ISSUE TITLE
Autosub Bootstrapbill keeps stopping

### ISSUE THREAD

**Issue by McEnnes** [Donny87/autosub-bootstrapbill#148]
Hi,
I am running version 0.6.3. on a Synology ds213+ with DSM 5.2-5592 Update 2
The program keeps stopping again and again.
I allready de installed it and installed it again.
I cannot find anything about it being stopped in the debug log.
Wahat can i do?

**Comment by MichaelB1105** [comment]
Same issue here!
Version 0.6.3-3
DSM 5.2-5592 Update 2

**Comment by McEnnes** [comment]
After three re installs and filling out a lot of name mappings, it seems stable again.
